### ISSUE TITLE
Regression Task

### ISSUE THREAD

**Issue by joelmac** [tkipf/keras-gcn#13]
Hi,

I'm having a bit of trouble getting the GCN to work for me.  I am currently trying to accomplish the following task:
given X in R^N and Y in R^N find a function mapping X to Y.  Here I know both X and Y correspond to values on the vertices of a graph and I have a dataset of many rows mapping X to Y.

I have installed the keras-gcn module that you've so graciously provided and done the updates suggested by buashh which update the code for keras 2.0.5 and python 3.5.  Using that I was able to get train.py to run correctly.

I have modified the code for the regression task I have at hand and gotten a little bit confused.

If I have say 1000 rows of X and Y data, should I also be passing the Laplacian 1000 times into the graph input layer?

So I would pass in` X_in = [<nx1000 array> X, <nxnx1000 array> T_0, <nxnx1000 array> T_1... etc]`?

**Comment by tkipf** [comment]
Thanks for your question. Just to make sure I understand your setting: In other words, you have N nodes each with two feature vectors of dim=1000 (i.e. X and Y)? Given an interaction graph between them (let's call this A), you would like to predict Y from X (and A)? In this case, simply feed X as data, A as adjacency matrix/graph and Y as 'labels'. Since you're trying to regress on 1000 values instead of the regular setting with multi-class classification, you'll have to find an appropriate loss function for your case (e.g. element-wise squared error, or something along these lines).

**Comment by joelmac** [comment]
@tkipf , very nearly.  Except I am trying to use the chebyshev method for my filter.   So I have for the most part modified the "else" clause from your own code, which passes a list of chebyshev polynomials of the regularized laplacian, rather than the adjacency matrix.  
In my code below:
X_SHAPE
(36000, 118)
Y_SHAPE
(36000,118)
T_k = list of 6 Laplacians, each a 118x118 matrix.

I'm new to Keras so I'm not sure if the error is just something obvious on my part.

`Traceback (most recent call last):
  File "/home/archimedes/.local/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 654, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/archimedes/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 118 and 708 for 'graph_convolution_1/MatMul_6' (op: 'MatMul') with input shapes: [?,118], [708,118].
`

`L = kegra.utils.rescale_laplacian(kegra.utils.normalized_laplacian(A,True))

print(L)

T_k = kegra.utils.chebyshev_polynomial(L, MAX_DEGREE)

graph = [X] +T_k
support = MAX_DEGREE + 1
G = [keras.layers.Input(shape=(None,None), batch_shape=(None,None,None), sparse=False) for _ in range(support)]

print("X_SHAPE")
print(X.shape)
for g in graph:
    print(g.shape)
X_in = keras.layers.Input(shape=(X.shape[1],))

# Define model architecture
# NOTE: We pass arguments for graph convolutional layers as a list of tensors.
# This is somewhat hacky, more elegant options would require rewriting the Layer base class.
H = keras.layers.Dropout(0.5)(X_in)
H = kegra.layers.graph.GraphConvolution(118, support, activation='relu', W_regularizer=keras.regularizers.l2(5e-4))([H]+G)
H = keras.layers.Dropout(0.5)(H)
FINAL = kegra.layers.graph.GraphConvolution(Y.shape[1], support, activation='relu')([H]+G)

model = keras.models.Model(inputs=[X_in]+G, outputs=FINAL)
model.compile(loss='mse', optimizer=keras.optimizers.Adam(lr=0.01))

NB_EPOCH = 20
# Fit
print(Y.shape)
for epoch in range(1, NB_EPOCH+1):

    # Log wall-clock time
    t = time.time()

    # Single training iteration (we mask nodes without labels for loss calculation)

    model.fit(graph, Y, epochs=1, shuffle=False, verbose=1,batch_size=A.shape[0])
`

**Comment by joelmac** [comment]
Reposting to fix formatting
```
L = kegra.utils.rescale_laplacian(kegra.utils.normalized_laplacian(A,True))

print(L)

T_k = kegra.utils.chebyshev_polynomial(L, MAX_DEGREE)

graph = [X] +T_k
support = MAX_DEGREE + 1
G = [keras.layers.Input(shape=(None,None), batch_shape=(None,None,None), sparse=False) for _ in range(support)]

print("X_SHAPE")
print(X.shape)
for g in graph:
print(g.shape)
X_in = keras.layers.Input(shape=(X.shape[1],))
H = keras.layers.Dropout(0.5)(X_in)
H = kegra.layers.graph.GraphConvolution(118, support, activation='relu', W_regularizer=keras.regularizers.l2(5e-4))([H]+G)
H = keras.layers.Dropout(0.5)(H)
FINAL = kegra.layers.graph.GraphConvolution(Y.shape[1], support, activation='relu')([H]+G)

model = keras.models.Model(inputs=[X_in]+G, outputs=FINAL)
model.compile(loss='mse', optimizer=keras.optimizers.Adam(lr=0.01))

NB_EPOCH = 20

print(Y.shape)
for epoch in range(1, NB_EPOCH+1):
    t = time.time()
    model.fit(graph, Y, epochs=1, shuffle=False, verbose=1,batch_size=A.shape[0])`
```

**Comment by tkipf** [comment]
Looks like you are concatenating the list of Chebyshev basis operators at some point, since you end up having an object of shape `[708,118]`. You should instead feed a list of 6 separate objects of shape `[118,118]` each. Also, your X and Y should be of shape `[118,36000]` (instead of `[36000,118]`), assuming 118 is the number of nodes in your graph. Maybe this is what causes the other problem (shape mismatch of the Laplacians).

**Comment by joelmac** [comment]
Worked!  I did see the error once you pointed out that I have been thinking sideways so to speak.   Very much appreciated as I've spent countless hours this weekend and today on this and am quite happy now!

**Comment by tkipf** [comment]
Awesome, good luck with your experiments!
