### ISSUE TITLE
index dislocation when spliting loading features

### ISSUE THREAD

**Issue by dawnranger** [tkipf/keras-gcn#14]
Thanks for your enlightening work!    

I think there is a minor mistake in function load_data, file utils.py, line 15:

> features = sp.csr_matrix(idx_features_labels[:, 1:-2], dtype=np.float32)

`idx_features_labels[:, 1:-2]` should be replaced by  `idx_features_labels[:, 1:-1]`, otherwise the last column of word attributes will be omitted.

**Comment by tkipf** [comment]
Thanks. The last column encodes label information in this case and is loaded in the next line.

**Comment by dawnranger** [comment]
I think you might misunderstand what I mean. I mean  the last column of word attributes but not the last column of idx_feature_labels.

since `idx_features_labels[:, 1:-2]` select attributes from the first column  to the last but two column from idx_feature_labels, and only the last column is loaded, so the last but one column is omitted

**Comment by gokceneraslan** [comment]
It should be idx_features_labels[:, 1:-1]

**Comment by tkipf** [comment]
Thanks, you're absolutely right. Fixed with https://github.com/tkipf/keras-gcn/commit/49350a361552c186d94648744468221990574a4e
