### ISSUE TITLE
Error in train.py

### ISSUE THREAD

**Issue by IbrahimSalim76** [tkipf/keras-gcn#17]
I used the command python train.py from Anaconda prompt and I got the following error

(C:\gcn-master\gcn>python train.py
Traceback (most recent call last):
  File "train.py", line 59, in <module>
    model = model_func(placeholders, input_dim=features[2][1], logging=True)
  File "C:\Users\Ibrahim\Anaconda3\lib\site-packages\gcn-1.0-py3.6.egg\gcn\model
s.py", line 145, in __init__
    self.build()
  File "C:\Users\Ibrahim\Anaconda3\lib\site-packages\gcn-1.0-py3.6.egg\gcn\model
s.py", line 42, in build
    self._build()
  File "C:\Users\Ibrahim\Anaconda3\lib\site-packages\gcn-1.0-py3.6.egg\gcn\model
s.py", line 170, in _build
    logging=self.logging))
  File "C:\Users\Ibrahim\Anaconda3\lib\site-packages\gcn-1.0-py3.6.egg\gcn\layer
s.py", line 184, in __init__
    self.phase_train = placeholders['phase_train']
KeyError: 'phase_train'

Also, the file train.py cann't detect the line 
    from gcn.utils import *
By the way, I'm using Spyder 3.2.4 (python 3.6.2)

Thanks

**Comment by tkipf** [comment]
Wrong version of keras?

**Comment by IbrahimSalim76** [comment]
Do you mean I have to install a specific version?If yes, what’s the appropriate version?


Sent from Yahoo Mail for iPhone


On Tuesday, November 28, 2017, 2:31 PM, Thomas Kipf <notifications@github.com> wrote:


Wrong version of keras?

**Comment by tkipf** [comment]
Version 1.0.9 (with the appropriate TensorFlow version) should work fine, for example.

**Comment by IbrahimSalim76** [comment]
Thanks. I’ll try doing that 


Sent from Yahoo Mail for iPhone


On Tuesday, November 28, 2017, 3:10 PM, Thomas Kipf <notifications@github.com> wrote:


Version 1.0.9 (with the appropriate TensorFlow version) should work fine, for example.

**Comment by IbrahimSalim76** [comment]
Hi Dr Thomas,
Regarding the version of keras, I have (Keras (2.0.8)). Is it OK?

Furthermore, Could you please provide me more explanation about the following command?
export PYTHONPATH="C:/Users/Ibrahim/Desktop/Fall_2017/Brain_Network/Papers/Ben_Hamza_Papers/gcn-master/:$PYTHONPATH” 
Where can I run this command?
Regards
Ibrahim



    On Tuesday, November 28, 2017, 3:10:15 PM EST, Thomas Kipf <notifications@github.com> wrote:  
 
 
Version 1.0.9 (with the appropriate TensorFlow version) should work fine, for example.

**Comment by tkipf** [comment]
I am not very familiar with your setup in Windows (+Anaconda). I would recommend running this on a UNIX system, otherwise it is probably best if you familiarized yourself with the intricacies of your setup and how you can install packages there or add packages to your python path.

**Comment by IbrahimSalim76** [comment]
Thank you so much for your collaboration

**Comment by IbrahimSalim76** [comment]
It worked. 
I just add the line :
'phase_train': tf.placeholder(tf.int32) in placeholders in the train.py file

Thank you so much
