### ISSUE TITLE
use keras gcn+ lstm,,with dynamic graph G at each time step

### ISSUE THREAD

**Issue by DanqingZ** [tkipf/keras-gcn#20]
Hi Thomas, this works is great and very useful to me!
I noticed that the current implementation of constructing graph G, is based on real-valued input adjacency matrix A. But if the graph is dynamic, then this adjacency matrix also changes over time, then I am thinking maybe we need to build the tensor G based on another adjacency tensor A instead of real-valued matrix? 
I might have some stupid idea that is wrong. Look forward to your suggestions!

**Comment by tkipf** [comment]
Yes, for dynamic graphs you will have to think of some other data structure. You can provide a list of sparse adjacency matrices, for example.
