### ISSUE TITLE
About the adjacency Matrix A coding

### ISSUE THREAD

**Issue by zhangxiaozao** [tkipf/keras-gcn#21]
Hello, I'm puzzled about the adjacency matrix A.
Paper said that A˜ = A + IN, but the code computed the adjacency A as "adj = adj + adj.T.multiply(adj.T > adj) - adj.multiply(adj.T > adj)", where is the IN? Did I miss it?
Thank you very much! Looking forward to your reply!

**Comment by tkipf** [comment]
The identity matrix is added in this function in `train.py`: `preprocess_adj(...)` (which, in turn, is defined in `utils.py`). Hope this helps.

**Comment by zhangxiaozao** [comment]
Yes! I got it! It's so careless of me... I have found it jut now.
Thank you very much!
