### ISSUE TITLE
About the call() in the graph.py

### ISSUE THREAD

**Issue by zhangxiaozao** [tkipf/keras-gcn#23]
I have several questions about the call() in the graph.py
1>Does the "basis" represent for Aˆ (Aˆ = D˜ ^-0.5 A˜D˜ ^-0.5) ?
2>I saw the "support"=1, does it mean that the "supports" only contains one example's new feature ?If so, where are other examples' new features?

Besides, for the first graph layer, the "inputs" contains Aˆ, but for the second graph layer, how is Aˆ contained in the "inputs"?
Thank you very much! Look forward for your reply! Thanks!

**Comment by tkipf** [comment]
Yes, the variable `basis` for the simple GCN model represents the renormalized adjacency matrix. Support=1 just means we're using a single basis. Support > 1 is required if you, e.g., use a polynomial basis with multiple terms.
