### ISSUE TITLE
ImportError: cannot import name initializations

### ISSUE THREAD

**Issue by almugabo** [tkipf/keras-gcn#4]
from kegra.layers.graph import GraphConvolution, GraphInput
gives the error 
**ImportError: cannot import name initializations**

the errors is due to 
----> 3 from keras import activations, initializations
and it comes when using both tensorflow or theano as backend

**Comment by tkipf** [comment]
Thanks for catching this. kegra currently only supports keras 1.x versions (1.0.9 or higher). keras 2.0 introduced some breaking changes to the API, such as renaming `initialisations` to `initializers`. I will push an update for keras 2.x support in the near future. For now, I recommend using keras 1.x for this project.

**Comment by tkipf** [comment]
Fixed with https://github.com/tkipf/keras-gcn/pull/10
