### ISSUE TITLE
Error running train.py

### ISSUE THREAD

**Issue by owang** [tkipf/keras-gcn#6]
`ValueError: Dimensions must be equal, but are 16 and 1432 for 'graph_convolution_2/MatMul' (op: 'MatMul') with input shapes: [?,16], [1432,7].`

This is from

  ```
File "kegra/train.py", line 57, in <module>
    Y = GraphConvolution(y.shape[1], support, activation='softmax')([H]+G)
  File "/Users/owang/Library/Python/2.7/lib/python/site-packages/keras/engine/topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)
  File "kegra/graph.py", line 143, in call
    output = K.dot(supports, self.W)
```

**Comment by tkipf** [comment]
Thanks for reporting! Which version of keras are you using?

**Comment by owang** [comment]
2.0.5, I just saw from the other issue that this version is not supported yet! Thanks, I'll wait for the fix =)

**Comment by tkipf** [comment]
I'll look into it soon - will keep you updated!

**Comment by hafizimtiaz** [comment]
I am also facing the same issue using Keras 2.0.4.

**Comment by buaahsh** [comment]
I upgraded gcn for keras 2.0.5, you can try it in https://github.com/buaahsh/keras-gcn.
The code needs to be modified in three place in order to handle keras 2.X. 

- initializations -> initializers

- add self.is_placeholder = True in GraphInputLayer

- change get_output_shape_for into compute_output_shape in GraphConvolution

**Comment by tkipf** [comment]
Thanks! Feel free to make a pull request

**Comment by hafizimtiaz** [comment]
Hi @buaahsh 
I downloaded your repo. But it still shows the same error on line 57 of train.py

ValueError: Dimensions must be equal, but are 16 and 1432 for 'graph_convolution_4/MatMul' (op: 'MatMul') with input shapes: [?,16], [1432,7].

**Comment by tkipf** [comment]
Fixed with https://github.com/tkipf/keras-gcn/pull/10
